server.port=9220
# Database URL, username, password
spring.datasource.url=jdbc:postgresql://localhost:5432/taskdbdetails
spring.datasource.username=postgres
spring.datasource.password=Database@2026

# JDBC driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate config
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Show SQL statements (optional)
spring.jpa.show-sql=true
